v1:
	docker build -t celfring/guestbook:v1 -f Dockerfile.v1 --rm .
	docker push celfring/guestbook:v1

v2:
	docker build -t celfring/guestbook:v2 -f Dockerfile.v2 --rm .
	docker push celfring/guestbook:v2
